### ISSUE TITLE
Tests broken on Plone 5.

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.noindexing#3]
In PR #2 @gotcha has given us Plone 5 support. But the test setup is broken on 5.2:

```
Error in test testMultiApplyAndUnapply (collective.noindexing.tests.test_functional.TestNoIndexingApplied)
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp27m/unittest2-1.1.0-py2.7.egg/unittest2/case.py", line 67, in testPartExecutor
    yield
  File "/Users/maurits/shared-eggs/cp27m/unittest2-1.1.0-py2.7.egg/unittest2/case.py", line 625, in run
    testMethod()
  File "/Users/maurits/community/collective.noindexing/collective/noindexing/tests/test_functional.py", line 75, in testMultiApplyAndUnapply
    doc = self._makeOne()
  File "/Users/maurits/community/collective.noindexing/collective/noindexing/tests/test_functional.py", line 38, in _makeOne
    return make_test_doc(self.layer['portal'])
  File "/Users/maurits/community/collective.noindexing/collective/noindexing/testing.py", line 42, in make_test_doc
    new_id = portal.generateUniqueId('Document')
AttributeError: 'RequestContainer' object has no attribute 'generateUniqueId'
```

The `generateUniqueId` script is gone on Plone 5.2 I think, or has moved to `Products.Archetypes`.

Trying it on Plone 5.1:

```
Error in test testNormalIndexing (collective.noindexing.tests.test_functional.TestNormalIndexing)
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp27m/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/Users/maurits/community/collective.noindexing/collective/noindexing/tests/test_functional.py", line 27, in testNormalIndexing
    doc = self._makeOne()
  File "/Users/maurits/community/collective.noindexing/collective/noindexing/tests/test_functional.py", line 20, in _makeOne
    return make_test_doc(self.layer['portal'])
  File "/Users/maurits/community/collective.noindexing/collective/noindexing/testing.py", line 43, in make_test_doc
    portal.invokeFactory('Document', new_id)
  File "/Users/maurits/shared-eggs/cp27m/Products.CMFCore-2.2.13-py2.7.egg/Products/CMFCore/PortalFolder.py", line 292, in invokeFactory
    return pt.constructContent(type_name, self, id, RESPONSE, *args, **kw)
  File "/Users/maurits/shared-eggs/cp27m/Products.CMFCore-2.2.13-py2.7.egg/Products/CMFCore/TypesTool.py", line 831, in constructContent
    raise ValueError('No such content type: %s' % type_name)
ValueError: No such content type: Document
```

We don't care about 5.0.
On 4.3 the tests pass.
We don't care about Plone 4.2 or earlier.

So a wishlist:

- [x] Enable Travis and add Travis config.
- [x] Make sure the tests pass on 4.3, 5.1, 5.2.
- [x] On 5.2 preferably on Python 2 and 3.
- [x] A test run with and one without Archetypes would be nice. I guess the Python 2 one will be with Archetypes, and the Python 3 one obviously without.
- [x] Update the compatibility notes in the README and the classifiers in `setup.py`.

Preferably we would do this before a release. But I guess a 2.0.0b1 release would be fine already.

**Comment by mauritsvanrees** [comment]
I have released 2.0.0b1.

**Comment by gotcha** [comment]
See #4

**Comment by gotcha** [comment]
@mauritsvanrees Tests pass now. See also #4
